### ISSUE TITLE
Can't Create Live Trade from Paper Trade

### ISSUE THREAD

**Issue by Bradperu1** [aqs-base/acuitas-issues#1]
I just performed a fresh install of Crowtrader Final Version 1.1.0.  I can successfully setup a paper trade using Theta/BTC, Bolinger Band.  The paper trade sets up correctly but when I attempt to create a live trade the "Create" button is not clickable.  I have tried editing any and all settings and even tried a different browser.

My system specs
Windows Server 2016 Datacenter
Processor: Intel Xeon CPU E5-2660 0 @2.20GHz (3 processors)
Installed Ram: 4.00 GB
64-bit Operating System, x64-based processor

Browsers Used: Brave Version 1.9.72 Chromium: 81.0.4044.138 (Official Build) (64-bit)
![live create button](https://user-images.githubusercontent.com/66044794/83087703-e276df80-a05f-11ea-9f9b-58096f008694.jpg)

**Comment by nibarulabs** [comment]
We are trying to reproduce this and will post updates here. Thanks.

**Comment by nibarulabs** [comment]
Quick question: does this happen for all pairs? What happens if you reload the browser? Thx.

**Comment by Bradperu1** [comment]
Looks like it happens on all pairs.  When I inspected the element for the button I found a disabled class .  When I edited it or removed "disabled" shown in the screenshot I was able to start a live trade with the button.
![Disabled Class](https://user-images.githubusercontent.com/66044794/83165342-61f5c480-a0db-11ea-8f02-105586cffe63.JPG)

**Comment by Bennywestdyk** [comment]
I am having same issue, with every pair.
windows 10, AMD A6-9210, brave browser

**Comment by nibarulabs** [comment]
@Bennywestdyk can you provide a screenshot of all the form fields? I am trying to fill everything in so I can try to figure out what's going on. Thx.

**Comment by Bennywestdyk** [comment]
![Screenshot (12)](https://user-images.githubusercontent.com/66122375/83271313-d7ab7e80-a208-11ea-9031-f695abceb03a.png)

![Screenshot (13)](https://user-images.githubusercontent.com/66122375/83271324-dd08c900-a208-11ea-82ef-d17b4ce6c640.png)


Here you go. Let me know if you need anything else.

**Comment by Bennywestdyk** [comment]
Not working on brave or chrome

**Comment by nibarulabs** [comment]
@Bennywestdyk thanks, taking a look now.

**Comment by nibarulabs** [comment]
@Bennywestdyk @Bradperu1 Found the issue and it's fixed. I have a few more things to wrap up today and will try to get 1.1.1 out which will include this update. Thx for reporting this. 👍
