### ISSUE TITLE
Coinbase - Bollinger Band Trails - Live Trading - BCH/USD - Sell trade not equal to Buy trade

### ISSUE THREAD

**Issue by SentrySkills** [aqs-base/acuitas-issues#10]
![image](https://user-images.githubusercontent.com/71289772/93408171-e3778b00-f861-11ea-92be-f462709fe87d.png)

**Comment by nibarulabs** [comment]
@SentrySkills can you confirm that the buy/sell equal bug has been fixed? Thanks.

**Comment by SentrySkills** [comment]
Fixed!

**Comment by nibarulabs** [comment]
This will be out in 1.1.3. Fixed in code.
