### ISSUE TITLE
Coinbase - Bollinger Band Trails - Live Trading - ETH/USD - Sell trade not equal to Buy trade

### ISSUE THREAD

**Issue by SentrySkills** [aqs-base/acuitas-issues#11]
![image](https://user-images.githubusercontent.com/71289772/93408307-4701b880-f862-11ea-90bc-761374ea92a6.png)

**Comment by nibarulabs** [comment]
Dupe of #10

**Comment by nibarulabs** [comment]
This will be out in 1.1.3. Fixed in code.
