### ISSUE TITLE
Coinbase - Bollinger Band Trails - Live Trading - LTC/USD - Sell trade not equal to Buy trade

### ISSUE THREAD

**Issue by SentrySkills** [aqs-base/acuitas-issues#12]
![image](https://user-images.githubusercontent.com/71289772/93408448-92b46200-f862-11ea-900c-d79631588113.png)

**Comment by nibarulabs** [comment]
Dupe of #10

**Comment by nibarulabs** [comment]
This will be out in 1.1.3. Fixed in code.
