### ISSUE TITLE
Coinbase - Bollinger Band Trails - Live Trading - DASH/USD - Sell trade not equal to Buy trade

### ISSUE THREAD

**Issue by SentrySkills** [aqs-base/acuitas-issues#13]
![image](https://user-images.githubusercontent.com/71289772/93408570-e6bf4680-f862-11ea-9b03-f223e38fe21f.png)

**Comment by nibarulabs** [comment]
Dupe of #10

**Comment by nibarulabs** [comment]
This will be out in 1.1.3. Fixed in code.
