### ISSUE TITLE
Coinbase - Crow EMA Sniper - Live Trading - BCH/USD - Sell trade not equal to Buy trade

### ISSUE THREAD

**Issue by SentrySkills** [aqs-base/acuitas-issues#15]
![image](https://user-images.githubusercontent.com/71289772/93412187-ae236b00-f86a-11ea-81f2-7b042d9b9daa.png)

**Comment by nibarulabs** [comment]
Dupe of #10

**Comment by nibarulabs** [comment]
This will be out in 1.1.3. Fixed in code.
