### ISSUE TITLE
Coinbase - Crow EMA Sniper - Live Trading - LTC/USD - Sell trade not equal to Buy trade

### ISSUE THREAD

**Issue by SentrySkills** [aqs-base/acuitas-issues#16]
![image](https://user-images.githubusercontent.com/71289772/93412296-e32fbd80-f86a-11ea-9dea-f585f7ddbe2e.png)

**Comment by nibarulabs** [comment]
Dupe of #10

**Comment by nibarulabs** [comment]
This will be out in 1.1.3. Fixed in code.
