### ISSUE TITLE
MacBook issue

### ISSUE THREAD

**Issue by walaawahba85** [aqs-base/acuitas-issues#24]
I’m having trouble opening the bot on MacBook.

1- downloaded the cryptotrader v1.2.1
2- downloaded the jdk8 as instructed in the guide
3- opened the brave browser and did the setup on  the local host 
4- tried to open the file cryptotrader server.Jar in the cryptotrader folder, but doesn’t work. Am I trying to open the wrong file?! I really don’t know how to move on from here

**Comment by nibarulabs** [comment]
There is a guide here that details how to run everything on a mac.

https://crowtrader.com/the-crowtrader-mac-install-guide/
