### ISSUE TITLE
Issue - Coinbase - Live - Sell not equal to Buy

### ISSUE THREAD

**Issue by SentrySkills** [aqs-base/acuitas-issues#25]
Buy and Sell orders are not equal. This causes "change" to build upon exchange. All pairs affected.

![image](https://user-images.githubusercontent.com/71289772/102524082-780ea680-4066-11eb-93d9-08d74f7fe8a3.png)
![image](https://user-images.githubusercontent.com/71289772/102524424-fbc89300-4066-11eb-88ba-e7d27e51cdf0.png)

Database and logs are saved on my end, just PM me on Telegram "Eric" 

Crowtrader1217200051.zip

**Comment by nibarulabs** [comment]
Fixed in 1.2.2
