### ISSUE TITLE
Issue - Fee's not Calculated in Profit Exit

### ISSUE THREAD

**Issue by SentrySkills** [aqs-base/acuitas-issues#26]
![image](https://user-images.githubusercontent.com/71289772/102578467-3ca4c400-40c8-11eb-802c-e8c43e15eb79.png)
Fee is 0.4%
Profit % 0.75%

Buy Price is $652.02
Exit Price is $656.91 (0.75%) missing 0.4%
Should Exit at ~$659.52

**Comment by nibarulabs** [comment]
Fixed in 1.2.2
