### ISSUE TITLE
Market sell and market buy order buttons still not working

### ISSUE THREAD

**Issue by Mit4Code** [aqs-base/acuitas-issues#30]
Nothing happens. I see this screen and it just stays there. I click after a while, it disappears and nothing happen.
![image](https://user-images.githubusercontent.com/49874678/106307509-5dc80b00-6257-11eb-88fd-9fb41623b54b.png)
![image](https://user-images.githubusercontent.com/49874678/106344920-7ad6fb00-62a4-11eb-8137-14574084a94a.png)

**Comment by nibarulabs** [comment]
Is this paper trading or live trading. What version of the bot?

**Comment by COBRA-StakePool** [comment]
In papertrade if works fine with 1.2.3 but just works some times at live trade. Most of the time it's just staying like up there 👆

**Comment by Mit4Code** [comment]
> Is this paper trading or live trading. What version of the bot?

In the background it can be seen that is live trading. Version 1.2.3.

**Comment by nibarulabs** [comment]
This is slated for fix in the next 1.3.0 release. Thanks.

**Comment by nibarulabs** [comment]
Fixed in 1.3.0.
