### ISSUE TITLE
Live Trading not opening trades

### ISSUE THREAD

**Issue by SentrySkills** [aqs-base/acuitas-issues#9]
I have a Coinbase Pro API with View/Trade, Running ver 1.1.2, Windows 10
![1](https://user-images.githubusercontent.com/71289772/93130896-381fd800-f6a1-11ea-8120-4e136319340e.PNG)

**Comment by nibarulabs** [comment]
@SentrySkills thx. I have been working with another user on this and will have an update out soon. Still need to go through more testing. 👍
